#!/bin/sh

IPTABLES=/sbin/iptables

ACCEPT_SOURCE_MAKE(){
  echo "start accept_source_make : $1"
  MAX=`cat $2 | grep -v '^#' | grep . | wc -l`
  COUNT=0
  $IPTABLES -N ACCEPT_${1}
  for addr in `cat $2 | grep -v '^#' | grep .`
  do
    COUNT=`expr $COUNT + 1`
    echo "COUNT = $COUNT/$MAX"
    $IPTABLES -A ACCEPT_${1} -s $addr -j ACCEPT
  done 
  echo "end accept_source_make : $1"
}

DROP_SOURCE_MAKE(){
  echo "start drop_source_make : $1"
  MAX=`cat $2 | grep -v '^#' | grep . | wc -l`
  COUNT=0
  $IPTABLES -N DROP_${1}
  for addr in `cat $2 | grep -v '^#' | grep .`
  do
    COUNT=`expr $COUNT + 1`
    echo "COUNT = $COUNT/$MAX"
    $IPTABLES -A DROP_${1} -s $addr -m limit --limit 1/s -j LOG --log-prefix "[TABLES DENY_${1}] : "
    $IPTABLES -A DROP_${1} -s $addr -j DROP
  done 
  echo "end drop_source_make : $1"
}


ACCEPT_SOURCE_MAKE SOFTBANK ./carrier/softbank.lst
ACCEPT_SOURCE_MAKE AU ./carrier/au.lst
ACCEPT_SOURCE_MAKE DOCOMO ./carrier/docomo.lst

DROP_SOURCE_MAKE SOFTBANK ./carrier/softbank.lst
DROP_SOURCE_MAKE AU ./carrier/au.lst
DROP_SOURCE_MAKE DOCOMO ./carrier/docomo.lst
